[package]
name = "youtube-brainz-api"
version = "1.0.0"
edition = "2021"

[dependencies]
actix-web = "4"
awc = { version = "3.0.0", features = ["rustls"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.79"
urlencoding = "2.1.0"
levenshtein = "1.0.5"
regex = "1"